version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: glowbook_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: glowbook
      POSTGRES_PASSWORD: glowbook
      POSTGRES_DB: glowbook_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
