// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    // Migrasi (`migrate deploy`/`migrate dev`) memakai koneksi direct Neon;
    // fallback ke DATABASE_URL supaya dev lokal tanpa DIRECT_DATABASE_URL tetap jalan.
    // Runtime PrismaService TIDAK memakai file ini — tetap pakai DATABASE_URL pooled.
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
